# NUMPY - Multidimensional Data Arrays

It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. NumPy brings the computational power of languages like C and Fortran to Python, a language much easier to learn and use.

In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.1'

In [3]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x00000243C07F2040>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +

## What is Array?

![](image/array.png)

In [4]:
# Python List

a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

In [5]:
print(a+b)
print(a*b)

[1, 2, 3, 4, 5, 6, 7, 8]


TypeError: can't multiply sequence by non-int of type 'list'

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 



In [6]:
a_array = np.array(a)
b_array = np.array(b)

print(a_array + b_array)
print(a_array / b_array)

[ 6  8 10 12]
[0.2        0.33333333 0.42857143 0.5       ]


## Creating `numpy` arrays

There are some ways to initialize new numpy arrays:
* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### Lists

In [7]:
# vector: the argument to the array function is a list
v = np.array([1, 2, 3, 4, 5])

v.shape

(5,)

In [8]:
# matrix: the argument to the array function is a nested list
m = np.array([[1, 2, 3], [4, 5, 6]])

m.shape

(2, 3)

The `v` and `m` objects are both of the type `ndarray` that the `numpy` module provides.

In [9]:
type(v), type(m)

(numpy.ndarray, numpy.ndarray)

In [10]:
a = [1,2,3]

In [11]:
type(a)

list

The difference between the `v` and `m` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [12]:
v.shape

(5,)

In [13]:
m.shape

(2, 3)

The number of elements in the array is available through the `ndarray.size` property

In [14]:
m.size

6

`numpy.ndarray` looks very similiar to the `list`. So, why not use the list instead?
`numpay.ndarray` is used for several reason:
1. Lists are very general. They can contain any kind of object. They do not support mathematical functions such as matrix and dot multiplication, etc. 
2. Numpy arrays are statically typed and homogenous. The type of the elements is determined when the array is created
3. Numpy arrays are memory efficient
4. It is fast for implementation of mathematical function

We can see the type of data of an array using `dtype`

In [15]:
one_dimension = np.array([1, 2, 3])

two_dimension = np.array([[4, 5, 6],
                          [7, 8, 9]])

two_dimension

##Tugas:
#membuat array 1 dimensi 7, 
#membuat array 2 dimensi 3, 3
#membuat array 3 dimensi 4, 4, 4

array([[4, 5, 6],
       [7, 8, 9]])

In [16]:
# Soal kedua

second_answer = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

# Print hasil
second_answer

# Shape
second_answer.shape

(3, 3)

In [17]:
# Soal ketiga
# Buatlah array 3 dimensi dg ashape 4, 4, 4

# answer
third_answer = np.array([[[1, 2, 3, 5],
                          [4, 5, 6, 6],
                          [7, 8, 9, 8],
                          [7, 8, 9, 8]],
                         
                         [[1, 2, 3, 8],
                          [4, 5, 6, 8],
                          [7, 8, 9, 8],
                          [7, 8, 9, 8]],
                         
                         [[1, 2, 3, 8],
                          [4, 5, 6, 8],
                          [7, 8, 9, 8],
                          [7, 8, 9, 8]],
                         
                         [[1, 2, 3, 8],
                          [4, 5, 6, 8],
                          [7, 8, 9, 8],
                          [7, 8, 9, 8]]])

# Print hasil
third_answer

# Shape
third_answer.shape

(4, 4, 4)

In [18]:
ones = np.ones((7, 7), dtype=int)

# Print ones
ones

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [19]:
m = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=float)

m

array([[1., 2., 3.],
       [4., 5., 6.]])

Common data types that can be used with `dtype` are: `int`, `float`, `complex`, `bool`, `object`, etc.

### Create Matrix Zeros

In [20]:
# One dimension

zeros_matrix = np.zeros(5)

zeros_matrix

array([0., 0., 0., 0., 0.])

In [21]:
#two dimension

zeros_matrix2 = np.zeros((5,2))
zeros_matrix2

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
# should  be in tuple format

zeros_matrix2 = np.zeros((5,2)) # 5 rows, 2 columns
zeros_matrix2 

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### Matrix ones

In [23]:
#one dimension

matrix_ones = np.ones(5)
matrix_ones 

array([1., 1., 1., 1., 1.])

In [24]:
#3 dimension

matrix_ones2 = np.ones((3, 4, 2)) #3 rows, 4 columns, 2 depth
matrix_ones2

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

## > Exercise 1

1. Create a matrix from a list which has 4 rows and 3 columns

2. Create the following matrix
![](image/lat11.png)

3. Create a 2D matrix with size of 10

4. Create a 3D matrix of ones which has 2 rows, 3 columns, and 3 depth

5. Make the following arrays from zeros arrays and with for loops
![](image/exercise1.png)

### Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generate arrays of different forms. Some of the more common are:

**arange**

In [25]:
# create a range

x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [27]:
# create a range

x = np.arange(10, 20) # arguments: start, stop

x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
# create a range

x = np.arange(10, 20, 2) # arguments: start, stop, step

x

array([10, 12, 14, 16, 18])

In [29]:
x = np.arange(-1, 1, 0.1)

x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

The number 9.00000000e-01 already is a floating point number.
It's written in scientific notation and is equivalent to 9 * 10**-1 or 0.9.

#### linspace

In [30]:
# using linspace, both end points ARE included
np.linspace(0, 10, 10) #Unlike arange that uses step, linspace uses the number of sample

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

#### random data

In [31]:
from numpy import random

In [32]:
#uniform random numbers in [0,1]
random.rand(5,5)

array([[0.62240643, 0.4306355 , 0.04478311, 0.96088266, 0.69549425],
       [0.21243939, 0.41252319, 0.1112361 , 0.70287383, 0.26899004],
       [0.50259953, 0.16575843, 0.49404532, 0.75589599, 0.23617791],
       [0.1595711 , 0.48863246, 0.589151  , 0.89770719, 0.47305805],
       [0.88981771, 0.36088008, 0.08482428, 0.61556083, 0.37641939]])

In [33]:
# standard normal distributed random numbers
x = random.randn(5,5)
x

array([[ 1.07090276, -1.56982877, -0.77005184, -0.39756185,  0.75779832],
       [ 0.2275069 , -1.10337019, -1.75217232,  0.41171349,  0.06446458],
       [-1.13868347, -0.57461763,  0.99576324, -1.85198248, -1.31912443],
       [ 0.67267738,  0.23739039, -0.32489579,  1.02696704, -0.39920787],
       [-0.17187639, -0.10204731,  0.65267532, -0.59165379, -0.9560998 ]])

In [34]:
x.dtype

dtype('float64')

In [35]:
x = np.ones(2, dtype = np.int64)
x

array([1, 1], dtype=int64)

In [36]:
random.randint(10)

8

In [37]:
random.randint(2, 10, size=4)

array([3, 2, 9, 9])

In [38]:
random.randint(2, 10, size=(4,2,2))

array([[[6, 7],
        [4, 4]],

       [[6, 5],
        [3, 8]],

       [[5, 6],
        [4, 8]],

       [[7, 8],
        [4, 8]]])

## Exercise 2

1. Generate a 1-D array containing 5 random integers from 0 to 100:

2. Generate a 2-D array with 3 rows, each row contains 5 random integers from 0 to 100

3. Generate a 1-D array of 30 evenly spaced elements between 1.5 and 5.5, inclusive.